Add several Visualization tools
MobilityData/awesome-transit pull request #239
Opened 2024-01-14 22:39 UTC by Simha-Kalimipalli

Hello,

I've added 40 +transit visualization tools.  Ive also added some some subheadings in the visualizations section to add clarity.

2024-01-14 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CUTR-at-USF/awesome-transit?pullRequest=239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CUTR-at-USF/awesome-transit?pullRequest=239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CUTR-at-USF/awesome-transit?pullRequest=239) it.</sub>

2024-01-15 18:41 UTC, emmambd requested changes
Thanks for this large contribution @Simha-Kalimipalli! This really helps highlight transit maps for the broader community. 

I've suggested a few minor changes to fix a spam link and adjust the headings for ease of readability.

2024-01-15 18:41 UTC, emmambd commented on README.md
> +- [Brand New Subway](http://jpwright.net/subway/) - An interactive transportation planning game that lets players alter the NYC subway system to their heart's content.
This link goes to a spam website. I believe this is the right link: https://jpwright.github.io/subway/

2024-01-15 18:41 UTC, emmambd commented on README.md
> +##### Most General drawing applications are also useful for transit map drawing, including but not limited to:
Since this is a subheading, it can be written like one for easier skimming (e.g General Drawing Applications for Making Visualizations)

2024-01-15 18:41 UTC, emmambd commented on README.md
> +##### Most general GIS ( are also useful for transit map drawing, including but not limited to:
Like above: 

Since this is a subheading, it can be written like one for easier skimming (e.g General GIS for Making Visualizations)

2024-01-15 18:52 UTC, Simha-Kalimipalli commented
HI Ive opened a new pull request with the requested edits

2024-01-15 18:53 UTC, emmambd approved these changes
LGTM! Thanks for the speedy changes @Simha-Kalimipalli.

2024-01-15 18:53 UTC, merged