Separate GTFS validators section.
MobilityData/awesome-transit pull request #49
Opened 2016-09-16 21:49 UTC by laidig

based on comments in #48

2016-09-17 01:32 UTC, barbeau commented on README.md
> +- [gtfs-validator](https://github.com/laidig/gtfs-validator) - A GTFS validator based on the Onebusaway GTFS Modules, runs in Java and is faster than the Google provided one.
IMHO, because this is a fork of a project we really need to list both here, and explain the differences as briefly as possible.

2016-09-17 01:32 UTC, barbeau requested changes

2016-09-19 01:59 UTC, luqmaan commented
Maybe add https://github.com/conveyal/gtfs-data-manager as well?

2016-09-21 10:57 UTC, luqmaan commented
❤️  Thanks for making the changes and adding all these details.

2016-09-21 10:57 UTC, luqmaan approved these changes

2016-09-21 10:57 UTC, merged