Autodoc for GTFS-rt
MobilityData/awesome-transit pull request #71
Opened 2017-05-29 17:13 UTC by laidig

2017-05-29 17:17 UTC, barbeau requested changes

2017-05-29 17:17 UTC, barbeau commented on README.md
> +- [GTFS-realtime Autodoc](https://laidig.github.io/gtfs-rt-autodoc/index.html) - Automatically generated documentation for GTFS-realtime, including some extensions.
Can you please move this to the top of the GTFS-RT section to mirror the GTFS section, and add link to the canonical markdown docs as well?

2017-05-29 17:23 UTC, laidig commented
Wait.. how come I never found that MD file until explicitly searching for it?? Is it one of life's great ironies that a Google supported project didn't have good SEO or does it look poorly upon my Google-fu?

2017-05-30 13:34 UTC, merged

2017-05-30 13:35 UTC, barbeau commented
Thanks @laidig!  Yeah, and on top of that the GTFS doc home is currently in flux, with canonical markdown on Github, the legacy developers.google site, and gtfs.org.  Hopefully we can unify some of this soon, as it's currently very confusing.