Add getting started section
MobilityData/awesome-transit pull request #76
Opened 2017-08-20 18:58 UTC by luqmaan

I don't know why I didn't just open a PR. 😞 

Closes #58

2017-08-20 19:03 UTC, barbeau requested changes

2017-08-20 19:03 UTC, barbeau commented on README.md
> +- [Transitland ](https://transit.land/) - A community curated list of GTFS/GTFS-realtime data feeds from around the world. If you're trying to get realtime data for some agency, this is a good place
I don't think Transitland had any realtime feeds yet, although it's on their roadmap. Transitfeeds.com is the best directory for realtime feeds that I know of.

2017-08-20 19:52 UTC, luqmaan commented on README.md
> +- [Transitland ](https://transit.land/) - A community curated list of GTFS/GTFS-realtime data feeds from around the world. If you're trying to get realtime data for some agency, this is a good place
Ah that's much better. Swapped them.

2017-08-20 20:00 UTC, luqmaan commented
I don't think we should list both transitland and transitfeeds in the Getting Started section.

They're both listed later in the page.

To me, the Getting Started section should be as short as possible and should be the things you should look at if it's your first time hearing about GTFS.

I don't think beginners need to know about both transitland and transitfeeds. They're so similar. And transitfeeds has more data than transitland.

2017-08-22 20:25 UTC, merged

2017-08-22 20:25 UTC, barbeau commented
Ok, works for me. Thanks!